name: Update README

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'  

jobs:
  update-readme:
    runs-on: ubuntu-latest
    timeout-minutes: 30 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai  

      - name: Run Python script to update README
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  
        run: python update_readme.py

      - name: Commit and push changes if README updated
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git diff --staged --quiet || git commit -m "Auto-update README.md [skip ci]"
          git push origin main || true  # Push if changes, ignore if no changes